Update version to 1.5.1 and update  .NET Tracer component to 1.28.4
DataDog/datadog-aas-extension pull request #69
Opened 2021-08-30 21:44 UTC by zacharycmontoya

2021-08-30 22:16 UTC, lucaspimentel approved these changes

2021-08-30 22:28 UTC, zacharycmontoya commented
@colin-higgins can we also bump the Datadog Agent version to 7.30.x for this official release?

2021-08-31 13:16 UTC, colin-higgins requested changes
We'll need to update the development version to `0.1.35` and as you suggested, we can update the agent version to `7.30.2` and then we'll verify the development package.

2021-08-31 18:13 UTC, colin-higgins approved these changes

2021-08-31 18:16 UTC, merged